version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${CONTAINER_NAME}
    ports:
      - "${PORT}:80"
    env_file:
      - .env
    restart: always
